extern	Opt_lp_of_son		new_opt_lp_of_son(Lp_of_son elem);
extern	Opt_lp_of_son		add_to_opt_lp_of_son(Opt_lp_of_son list, Opt_lp_of_son new);
extern	void			set_lp_set(Lp_of_father head);
extern	Lp_of_son		new_lp_e_lp(void);
extern	Lp_of_son		add_to_lp_e_lp(Lp_of_son head, Lp_of_son cur);
extern	Lp_of_father		new_multi_lp(void);
extern	Lp_of_father		add_to_multi_lp(Lp_of_father list, Lp_of_father element);
extern	int			edges_x_split(tree_ref first_brother, Graph production);
extern	Edge			corresponding_edge(tree_ref edge, Graph prod);
extern	Node			corresponding_node(tree_ref node, Graph prod);
extern	Lp_set			new_lp_set(List_of_multi_lp target);
extern	Lp_set			add_to_lp_set(Lp_set list, Lp_set elem);
extern	void			set_orientation_type_set(Lp_of_son head);
extern	void			set_lp_costs(Lp_of_son prod);
extern	void			set_lp_set_costs(Lp_of_father head);
extern	void			set_LP_costs(tree_ref father);
extern	void			set_LHS_costs(tree_ref father);
extern	int			is_in_set_of(Lp_set set, List_of_multi_lp to_find);
extern	void			set_LP_set(tree_ref father);
extern	void			set_lp_set_of_lp_of_son_one_level_higher(tree_ref son);
