# (C) Universitaet Passau, Michael Himsolt 1986-1993
#########################################################################
#									#
#			    GRAPHED makeFILE				#
#									#
#########################################################################

#
# Sourcefiles
#
CSOURCES = bends_minimize.c bends_sf.c
HSOURCES = minimal_bends_layout_export.h
MYFILES = $(HSOURCES) $(CSOURCES)

GRAPHEDDIR=../..
include ../makefile.template
include $(GRAPHEDDIR)/makefile.template



it :	$(MODULE).o

include makedepend
