/* Generated By:JJTree: Do not edit this line. ASTStatement.java */

package org.graffiti.plugins.ios.importers.dot.parser;

public class ASTStatement extends SimpleNode {
    public ASTStatement(int id) {
        super(id);
    }

    public ASTStatement(DOTParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(DOTParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
