//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Mar 15 11:00:21 CET 2004
//----------------------------------------------------

package de.chris.plugins.inputserializers.test;

/** CUP generated class containing symbol constants. */
public class sym {
    /* terminals */
    public static final int EDGE = 11;

    public static final int CBRACE = 9;

    public static final int INTEGER = 2;

    public static final int NODE = 10;

    public static final int SBRACE = 8;

    public static final int DIRECTED = 7;

    public static final int EOF = 0;

    public static final int TARGET = 5;

    public static final int GRAPH = 3;

    public static final int ID = 6;

    public static final int error = 1;

    public static final int SOURCE = 4;
}
