# (C) Universitaet Passau, Michael Himsolt 1986-1993
#########################################################################
#									#
#			    GRAPHED makeFILE				#
#									#
#########################################################################

#
# Sourcefiles
#
CSOURCES = fileselect.c auto_extension.c
HSOURCES = fileselect.h auto_extension.h
MYFILES = $(HSOURCES) $(CSOURCES)

CFLAGS += 
LDFLAGS += 

GRAPHEDDIR=../..
include ../makefile.template
include $(GRAPHEDDIR)/makefile.template



it :	$(MODULE).o

include makedepend
