# (C) Universitaet Passau, Michael Himsolt 1986-1993
#########################################################################
#									#
#			    GRAPHED makeFILE				#
#									#
#########################################################################


#
# Directories
#

#
# Sourcefiles
#
CSOURCES = flow_and_matching.c
HSOURCES = flowmatch.h
MYFILES = $(HSOURCES) $(CSOURCES)

GRAPHEDDIR = ../..

include ../makefile.template
include $(GRAPHEDDIR)/makefile.template


it :	$(MODULE).o

include makedepend
