/* Generated By:JJTree&JavaCC: Do not edit this line. DOTParserConstants.java */
package org.graffiti.plugins.ios.importers.dot.parser;

public interface DOTParserConstants {

    int EOF = 0;
    int SINGLE_LINE_COMMENT = 8;
    int MULTI_LINE_COMMENT = 9;
    int DIGRAPH = 11;
    int EDGE = 12;
    int GRAPH = 13;
    int NODE = 14;
    int STRICT = 15;
    int SUBGRAPH = 16;
    int EQ = 17;
    int LBRACE = 18;
    int RBRACE = 19;
    int EDGE_UNDIRECTED = 20;
    int EDGE_DIRECTED = 21;
    int LBRACKET = 22;
    int RBRACKET = 23;
    int COMMA = 24;
    int SEMICOLON = 25;
    int ID = 26;
    int HTML = 27;
    int $HtmlString = 28;
    int $BaseChar = 29;
    int $Ideographic = 30;
    int CombiningChar = 31;
    int $Digit = 32;
    int Extender = 33;
    int $EscapedCharacter = 34;
    int $NotWhitespaceNotQuoteNotEscape = 35;
    int $Letter = 36;
    int $Number = 37;
    int $UnquotedString = 38;
    int $QuotedString = 39;

    int DEFAULT = 0;
    int IN_SINGLE_LINE_COMMENT = 1;
    int IN_MULTI_LINE_COMMENT = 2;

    String[] tokenImage = { "<EOF>", "\" \"", "\"\\t\"", "\"\\n\"", "\"\\r\"",
            "\"\\f\"", "\"//\"", "\"/*\"", "<SINGLE_LINE_COMMENT>", "\"*/\"",
            "<token of kind 10>", "\"digraph\"", "\"edge\"", "\"graph\"",
            "\"node\"", "\"strict\"", "\"subgraph\"", "\"=\"", "\"{\"",
            "\"}\"", "\"--\"", "\"->\"", "\"[\"", "\"]\"", "\",\"", "\";\"",
            "<ID>", "<HTML>", "<$HtmlString>", "<$BaseChar>", "<$Ideographic>",
            "<CombiningChar>", "<$Digit>", "<Extender>", "<$EscapedCharacter>",
            "<$NotWhitespaceNotQuoteNotEscape>", "<$Letter>", "<$Number>",
            "<$UnquotedString>", "<$QuotedString>", };

}
