/* This software is distributed under the Lesser General Public License */
#ifndef GT_ATTRIBUTES_H
#define GT_ATTRIBUTES_H

//
// Attributes.h
//
// This file defines the classes
//   GT_Attribute_Base
//   GT_Attribut<T>
//   GT_Attributes
//   GT_List_of_Attributes
//
//------------------------------------------ CVS
//
// CVS Headers -- The following headers are generated by the CVS
// version control system. Note that especially the attribute
// Author is not necessarily the author of the code.
//
// $source: /home/br/CVS/graphlet/src/gt_base/Attributes.h,v $
// $Author: himsolt $
// $Revision: 1.2 $
// $Date: 1999/03/05 20:43:11 $
// $Locker:  $
// $State: Exp $
//
//------------------------------------------ CVS
//
// (C) University of Passau 1995-1999, Graphlet Project
//


#include "Attribute_Base.h"
#include "List_of_Attributes.h"

// #include "Attribute_int.h"
// #include "Attribute_double.h"
// #include "Attribute_string.h"
// #include "Attribute_list.h"

#endif
