// =============================================================================
//
//   SingleGraphElementEditComponent.java
//
//   Copyright (c) 2001-2006 Gravisto Team, University of Passau
//
// =============================================================================
// $Id: SingleGraphElementEditComponent.java 5768 2010-05-07 18:42:39Z gleissner $

/* Generated by Together */

package org.graffiti.plugin.editcomponent;

import javax.swing.JComboBox;
import javax.swing.JComponent;

import org.graffiti.graph.GraphElement;
import org.graffiti.plugin.Displayable;

/**
 * This class provides an edit component for graph elements.
 * 
 * @see javax.swing.JComboBox
 * @see NodeEditComponent
 * @see EdgeEditComponent
 * @see org.graffiti.graph.GraphElement
 */
public abstract class SingleGraphElementEditComponent extends
        GraphComponentEditComponent {

    /** The <code>GraphElement</code> to be edited. */
    protected GraphElement ge;

    /** The <code>CombobBox</code> for selecting a graph element. */
    protected JComboBox comboBox;

    /**
     * Constructs a new <code>SingleGraphElementEditComponent</code>.
     * 
     * @param disp
     *            DOCUMENT ME!
     */
    protected SingleGraphElementEditComponent(Displayable<?> disp) {
        super(disp);
    }

    /**
     * Returns a String suitable for the name column in the name value table.
     * 
     * @return a String suitable for the name column in the name value table.
     */
    public String getCaption() {
        return ge.getAttribute("graphics.label").getId();
    }

    /**
     * Returns the <code>ValueEditComponent</code>'s <code>JComponent</code>.
     * 
     * @return DOCUMENT ME!
     * 
     * @throws RuntimeException
     *             DOCUMENT ME!
     */
    public JComponent getComponent() {
        throw new RuntimeException("implement me");
    }

    /**
     * Sets the current value of the <code>Attribute</code> in the corresponding
     * <code>JComponent</code>.
     */
    @Override
    protected void setDispEditFieldValue() {
    }

    /**
     * Sets the graph component selectable by this edit component.
     */
    @Override
    public void setGraphComponent() {
    }
}

// -----------------------------------------------------------------------------
// end of file
// -----------------------------------------------------------------------------
