	extern	GraphEd_Menu_Proc call_menu_check_connectivity;
	extern	GraphEd_Menu_Proc call_menu_check_strong_biconnectivity;
	extern	GraphEd_Menu_Proc call_menu_check_biconnectivity;
	extern	GraphEd_Menu_Proc call_menu_check_strong_connectivity;

