/* Generated By:JJTree: Do not edit this line. ASTedgeRHS.java */

package org.graffiti.plugins.ios.importers.dot.parser;

public class ASTedgeRHS extends SimpleNode {
    public ASTedgeRHS(int id) {
        super(id);
    }

    public ASTedgeRHS(DOTParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(DOTParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
