BS_printf( set, mode )
NOT_IN_LIST
LI_reset_nodelabel_list() 
LI_add_nodelabel( str ) 
LI_get_number_of_nodelabel( str ) 
LI_get_nodelabel_of-number( nr ) 
LI_fshow_nodelabel_list( file ) 
LI_sizeof_nodelabel_list() 
LI_reset_edgelabel_list() 
LI_add_edgelabel( str )
LI_get_number_of_edgelabel( str ) 
LI_get_edgelabel_of-number( nr ) 
LI_fshow_edgelabel_list( file ) 
LI_sizeof_edgelabel_list() 
ERROR(x)
MISC_get_grammar_start_symbol( sgragra ) 
MISC_is_terminal( str ) 
PE_for_all_histories( pe, his ) 
PE_end_for_all_histories( pe, his ) 
PE_for_all_parsing_elements( plist, pe )
PE_end_for_all_parsing_elements( plist, pe )
PE_for_all_edges( pe, edge ) 
PE_end_for_all_edges( pe, edge ) 
PE_for_all_embeddings( pe, emb ) 
PE_end_for_all_embeddings( pe, emb ) 
PE_UNMARK( pe ) 
PE_MARK( pe ) 
PE_FIX( pe ) 
PE_IS_UNMARKED( pe ) 
PE_IS_MARKED( pe ) 
PE_IS_FIXED( pe ) 
EDGE_UNMARK( edge ) 
EDGE_MARK( edge ) 
EDGE_IS_UNMARKED( edge ) 
EDGE_IS_MARKED( edge ) 
EMB_UNMARK( emb ) 
EMB_MARK( emb ) 
EMB_IS_UNMARKED( emb ) 
EMB_IS_MARKED( emb ) 
SIZE_OF_GRAPH( graph ) 
PE_for_all_productions( grammar, prod )
PE_end_for_all_productions( grammar, prod ) 
PE_reset_grammar( Gram )
PE_dispose_grammar( Gram )
PE_reset_number_generator()	
