#
# Makefile
#
# This file is the Makefile for lib/graphlet.
#
#------------------------------------------
#
# $Source: /home/br/CVS/graphlet/lib/graphlet/GNUmakefile,v $
# $Author: himsolt $
# $Revision: 1.2 $
# $Date: 1999/03/05 20:39:16 $
# $Locker:  $
# $State: Exp $
#
#------------------------------------------
#
# (C) University of Passau 1995-1999, graphlet project
#


GRAPHLET_BASE_DIR=../..
SUBDIRS=etc examples config

include $(GRAPHLET_BASE_DIR)/lib/graphlet/config/common

all:	$(SUBDIRS)



##########################################
#
# Set emacs variables
#
##########################################

# ;;; Local Variables: ***
# ;;; End: ***
