/* Generated By:JJTree: Do not edit this line. .\DOTParserVisitor.java */

package org.graffiti.plugins.ios.importers.dot.parser;

public interface DOTParserVisitor {
    public Object visit(SimpleNode node, Object data);

    public Object visit(ASTparse node, Object data);

    public Object visit(ASTgraph node, Object data);

    public Object visit(ASTstmt_list node, Object data);

    public Object visit(ASTStatement node, Object data);

    public Object visit(ASTideq_stmt node, Object data);

    public Object visit(ASTattr_stmt node, Object data);

    public Object visit(ASTnode_stmt node, Object data);

    public Object visit(ASTnode_id node, Object data);

    public Object visit(ASTedge_stmt node, Object data);

    public Object visit(ASTsubgraph node, Object data);

    public Object visit(ASTedgeRHS node, Object data);

    public Object visit(ASTedgeop node, Object data);

    public Object visit(ASTattr_list node, Object data);

    public Object visit(ASTa_list node, Object data);
}
