#
# Makefile
#
# This file is the Makefile for graphlet/examples.
#
#------------------------------------------
#
# $Source: /home/br/CVS/graphlet/lib/graphlet/examples/GNUmakefile,v $
# $Author: himsolt $
# $Revision: 1.2 $
# $Date: 1999/03/05 20:39:48 $
# $Locker:  $
# $State: Exp $
#
#------------------------------------------
#
# (C) University of Passau 1995-1999, graphlet project
#


GRAPHLET_BASE_DIR=../../..
SUBDIRS=

include $(GRAPHLET_BASE_DIR)/lib/graphlet/config/common

all:	

install.local::
	$(INSTALL_MAKE_DIR) $(INSTALL_EXAMPLES_DIR)

##########################################
#
# Set emacs variables
#
##########################################

# ;;; Local Variables: ***
# ;;; tab-width: 4 ***
# ;;; tab-stop-list: (4 8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72) ***
# ;;; End: ***
